"""Stable Polars schemas for generated Parquet artifacts."""

from typing import Any

import polars as pl

_UTC_TIMESTAMP = pl.Datetime(time_zone="UTC")

_UTC_TIMESTAMP = pl.Datetime(time_zone="UTC")

# Dict insertion order is part of the output contract: it fixes Parquet column
# order as well as making the schemas easy to inspect in tests and tooling.
ENTITY_SCHEMAS: dict[str, dict[str, Any]] = {
    "customers": {
        "customer_id": pl.Utf8,
        "customer_type": pl.Utf8,
        "customer_status": pl.Utf8,
        "date_of_birth": pl.Date,
        "country": pl.Utf8,
        "city": pl.Utf8,
        "registration_date": _UTC_TIMESTAMP,
        "risk_segment": pl.Utf8,
        "income_band": pl.Utf8,
        "occupation_category": pl.Utf8,
        "preferred_channels": pl.List(pl.Utf8),
        "created_at": _UTC_TIMESTAMP,
        "updated_at": _UTC_TIMESTAMP,
        "valid_from": _UTC_TIMESTAMP,
        "valid_to": _UTC_TIMESTAMP,
        "system_from": _UTC_TIMESTAMP,
        "system_to": _UTC_TIMESTAMP,
    },
    "institutions": {
        "institution_id": pl.Utf8,
        "institution_type": pl.Utf8,
        "country": pl.Utf8,
        "institution_code": pl.Utf8,
        "risk_profile": pl.Utf8,
        "processing_latency_profile": pl.Utf8,
    },
    "accounts": {
        "account_id": pl.Utf8,
        "customer_id": pl.Utf8,
        "institution_id": pl.Utf8,
        "account_type": pl.Utf8,
        "currency": pl.Utf8,
        "opening_date": _UTC_TIMESTAMP,
        "closing_date": _UTC_TIMESTAMP,
        "status": pl.Utf8,
        "credit_limit": pl.Float64,
        "available_balance": pl.Float64,
        "ledger_balance": pl.Float64,
        "overdraft_limit": pl.Float64,
        "created_at": _UTC_TIMESTAMP,
        "updated_at": _UTC_TIMESTAMP,
        "valid_from": _UTC_TIMESTAMP,
        "valid_to": _UTC_TIMESTAMP,
        "system_from": _UTC_TIMESTAMP,
        "system_to": _UTC_TIMESTAMP,
    },
    "cards": {
        "card_id": pl.Utf8,
        "account_id": pl.Utf8,
        "customer_id": pl.Utf8,
        "scheme": pl.Utf8,
        "card_type": pl.Utf8,
        "status": pl.Utf8,
        "issued_at": _UTC_TIMESTAMP,
        "expires_at": _UTC_TIMESTAMP,
        "country": pl.Utf8,
        "network_token_enabled": pl.Boolean,
        "contactless_enabled": pl.Boolean,
        "online_enabled": pl.Boolean,
        "international_enabled": pl.Boolean,
        "daily_limit": pl.Float64,
        "transaction_limit": pl.Float64,
    },
    "merchants": {
        "merchant_id": pl.Utf8,
        "merchant_name": pl.Utf8,
        "merchant_category_code": pl.Utf8,
        "country": pl.Utf8,
        "city": pl.Utf8,
        "risk_segment": pl.Utf8,
        "acquirer_id": pl.Utf8,
        "online_only": pl.Boolean,
        "created_at": _UTC_TIMESTAMP,
    },
    "devices": {
        "device_id": pl.Utf8,
        "device_type": pl.Utf8,
        "os_family": pl.Utf8,
        "browser_family": pl.Utf8,
        "first_seen_at": _UTC_TIMESTAMP,
        "last_seen_at": _UTC_TIMESTAMP,
        "trusted": pl.Boolean,
        "device_fingerprint": pl.Utf8,
        "risk_score": pl.Float64,
    },
    "pix_keys": {
        "pix_key_id": pl.Utf8,
        "account_id": pl.Utf8,
        "customer_id": pl.Utf8,
        "institution_id": pl.Utf8,
        "key_type": pl.Utf8,
        "key_hash_or_synthetic_value": pl.Utf8,
        "created_at": _UTC_TIMESTAMP,
        "status": pl.Utf8,
    },
}

NETWORK_ENDPOINT_SCHEMA: dict[str, Any] = {
    "endpoint_id": pl.Utf8,
    "endpoint_type": pl.Utf8,
    "address_hash": pl.Utf8,
    "first_seen_at": _UTC_TIMESTAMP,
    "last_seen_at": _UTC_TIMESTAMP,
    "valid_from": _UTC_TIMESTAMP,
    "valid_to": _UTC_TIMESTAMP,
}

ENTITY_STATE_HISTORY_SCHEMA: dict[str, Any] = {
    "entity_id": pl.Utf8,
    "entity_type": pl.Utf8,
    "from_status": pl.Utf8,
    "to_status": pl.Utf8,
    "effective_at": _UTC_TIMESTAMP,
    "system_from": _UTC_TIMESTAMP,
    "system_to": _UTC_TIMESTAMP,
}

BEHAVIOR_PROFILE_SCHEMA: dict[str, Any] = {
    "behavior_profile_id": pl.Utf8,
    "customer_id": pl.Utf8,
    "spending_level": pl.Utf8,
    "typical_payment_hours": pl.List(pl.Int64),
    "hour_weights": pl.List(pl.Float64),
    "weekday_weights": pl.List(pl.Float64),
    "typical_countries": pl.List(pl.Utf8),
    "merchant_category_preferences": pl.List(pl.Utf8),
    "merchant_category_weights": pl.List(pl.Float64),
    "monthly_income": pl.Float64,
    "monthly_spending_budget": pl.Float64,
    "card_vs_transfer_preference": pl.Float64,
    "online_purchase_rate": pl.Float64,
    "travel_frequency": pl.Float64,
    "preferred_device_ids": pl.List(pl.Utf8),
    "trusted_device_count": pl.Int64,
}

PAYMENT_SCHEMA: dict[str, Any] = {
    "payment_id": pl.Utf8,
    "payment_rail": pl.Utf8,
    "payment_type": pl.Utf8,
    "payer_account_id": pl.Utf8,
    "payee_account_id": pl.Utf8,
    "merchant_id": pl.Utf8,
    "card_id": pl.Utf8,
    "amount": pl.Float64,
    "currency": pl.Utf8,
    "initiated_at": _UTC_TIMESTAMP,
    "current_status": pl.Utf8,
    "payer_institution_id": pl.Utf8,
    "payee_institution_id": pl.Utf8,
    "payer_pix_key_id": pl.Utf8,
    "payee_pix_key_id": pl.Utf8,
}

LEDGER_ENTRY_SCHEMA: dict[str, Any] = {
    "ledger_entry_id": pl.Utf8,
    "account_id": pl.Utf8,
    "payment_id": pl.Utf8,
    "event_id": pl.Utf8,
    "entry_type": pl.Utf8,
    "amount": pl.Float64,
    "currency": pl.Utf8,
    "occurred_at": _UTC_TIMESTAMP,
    "effective_at": _UTC_TIMESTAMP,
    "posted_at": _UTC_TIMESTAMP,
    "balance_after": pl.Float64,
}

PAYMENT_EVENT_SCHEMA: dict[str, Any] = {
    "event_id": pl.Utf8,
    "event_type": pl.Utf8,
    "event_version": pl.Int64,
    "payment_id": pl.Utf8,
    "customer_id": pl.Utf8,
    "account_id": pl.Utf8,
    "event_time": _UTC_TIMESTAMP,
    "source_created_at": _UTC_TIMESTAMP,
    "source_available_at": _UTC_TIMESTAMP,
    "ingested_at": _UTC_TIMESTAMP,
    "processed_at": _UTC_TIMESTAMP,
    "producer": pl.Utf8,
    "source_system": pl.Utf8,
    "schema_version": pl.Utf8,
    "correlation_id": pl.Utf8,
    "causation_id": pl.Utf8,
    "simulation_run_id": pl.Utf8,
    "scenario_id": pl.Utf8,
    "payment_rail": pl.Utf8,
    "payment_type": pl.Utf8,
    "payee_account_id": pl.Utf8,
    "merchant_id": pl.Utf8,
    "card_id": pl.Utf8,
    "device_id": pl.Utf8,
    "transport_partition": pl.Int64,
    "online": pl.Boolean,
    "amount": pl.Float64,
    "currency": pl.Utf8,
    "scenario_type": pl.Utf8,
    "scenario_trigger": pl.Utf8,
    "scenario_reason": pl.Utf8,
    "fraud_record_id": pl.Utf8,
    "affected_entity_ids": pl.List(pl.Utf8),
}

# Lifecycle events use the same stable envelope as all payment events. Keeping
# a named alias makes the contract explicit for consumers and tests.
PAYMENT_LIFECYCLE_EVENT_SCHEMA = PAYMENT_EVENT_SCHEMA
GRAPH_PAYMENT_EVENT_SCHEMA = {
    **PAYMENT_EVENT_SCHEMA,
    "ip_id": pl.Utf8,
}
GRAPH_MEMBERSHIP_SCHEMA = {
    "campaign_id": pl.Utf8,
    "pattern_type": pl.Utf8,
    "member_id": pl.Utf8,
    "member_type": pl.Utf8,
    "role": pl.Utf8,
    "valid_from": _UTC_TIMESTAMP,
    "valid_to": _UTC_TIMESTAMP,
    "source_event_id": pl.Utf8,
    "payment_id": pl.Utf8,
}
GRAPH_PATTERN_SCHEMA = {
    "pattern_id": pl.Utf8,
    "pattern_type": pl.Utf8,
    "campaign_id": pl.Utf8,
    "detected_at": _UTC_TIMESTAMP,
    "window_from": _UTC_TIMESTAMP,
    "window_to": _UTC_TIMESTAMP,
    "member_ids": pl.List(pl.Utf8),
    "source_event_ids": pl.List(pl.Utf8),
    "payment_ids": pl.List(pl.Utf8),
    "threshold": pl.Int64,
    "observed_value": pl.Float64,
    "invariant_status": pl.Utf8,
}

FRAUD_RECORD_SCHEMA: dict[str, Any] = {
    "fraud_record_id": pl.Utf8,
    "record_type": pl.Utf8,
    "scenario_id": pl.Utf8,
    "scenario_type": pl.Utf8,
    "fraud_truth": pl.Boolean,
    "trigger": pl.Utf8,
    "reason": pl.Utf8,
    "customer_id": pl.Utf8,
    "account_id": pl.Utf8,
    "card_id": pl.Utf8,
    "device_id": pl.Utf8,
    "merchant_id": pl.Utf8,
    "payment_id": pl.Utf8,
    "event_id": pl.Utf8,
    "occurred_at": _UTC_TIMESTAMP,
    "amount": pl.Float64,
    "currency": pl.Utf8,
    "correlation_id": pl.Utf8,
    "causation_id": pl.Utf8,
    "affected_entity_ids": pl.List(pl.Utf8),
}

FRAUD_ALERT_SCHEMA: dict[str, Any] = {
    "fraud_alert_id": pl.Utf8,
    "alert_type": pl.Utf8,
    "severity": pl.Utf8,
    "customer_id": pl.Utf8,
    "account_id": pl.Utf8,
    "card_id": pl.Utf8,
    "device_id": pl.Utf8,
    "merchant_id": pl.Utf8,
    "payment_id": pl.Utf8,
    "event_id": pl.Utf8,
    "fraud_record_id": pl.Utf8,
    "scenario_id": pl.Utf8,
    "scenario_type": pl.Utf8,
    "trigger": pl.Utf8,
    "reason": pl.Utf8,
    "alert_created_at": _UTC_TIMESTAMP,
    "amount": pl.Float64,
    "currency": pl.Utf8,
    "correlation_id": pl.Utf8,
    "causation_id": pl.Utf8,
    "simulation_run_id": pl.Utf8,
    "affected_entity_ids": pl.List(pl.Utf8),
}

FRAUD_CASE_SCHEMA: dict[str, Any] = {
    "fraud_case_id": pl.Utf8,
    "fraud_alert_id": pl.Utf8,
    "customer_id": pl.Utf8,
    "account_id": pl.Utf8,
    "card_id": pl.Utf8,
    "device_id": pl.Utf8,
    "merchant_id": pl.Utf8,
    "payment_id": pl.Utf8,
    "event_id": pl.Utf8,
    "fraud_record_id": pl.Utf8,
    "scenario_id": pl.Utf8,
    "scenario_type": pl.Utf8,
    "fraud_truth": pl.Boolean,
    "fraud_occurred_at": _UTC_TIMESTAMP,
    "alert_created_at": _UTC_TIMESTAMP,
    "case_opened_at": _UTC_TIMESTAMP,
    "case_closed_at": _UTC_TIMESTAMP,
    "fraud_confirmed_at": _UTC_TIMESTAMP,
    "label_available_at": _UTC_TIMESTAMP,
    "investigation_outcome": pl.Utf8,
    "loss_amount": pl.Float64,
    "recovered_amount": pl.Float64,
    "amount": pl.Float64,
    "currency": pl.Utf8,
    "correlation_id": pl.Utf8,
    "causation_id": pl.Utf8,
    "simulation_run_id": pl.Utf8,
    "affected_entity_ids": pl.List(pl.Utf8),
}
FRAUD_CASE_SCHEMA_M17 = {**FRAUD_CASE_SCHEMA, "case_reopened_at": _UTC_TIMESTAMP}

CASE_CONFIRMATION_SCHEMA: dict[str, Any] = {
    "confirmation_id": pl.Utf8,
    "fraud_case_id": pl.Utf8,
    "fraud_alert_id": pl.Utf8,
    "customer_id": pl.Utf8,
    "payment_id": pl.Utf8,
    "event_id": pl.Utf8,
    "fraud_record_id": pl.Utf8,
    "scenario_id": pl.Utf8,
    "scenario_type": pl.Utf8,
    "fraud_truth": pl.Boolean,
    "confirmed_at": _UTC_TIMESTAMP,
    "investigation_outcome": pl.Utf8,
    "amount": pl.Float64,
    "currency": pl.Utf8,
    "correlation_id": pl.Utf8,
    "causation_id": pl.Utf8,
    "simulation_run_id": pl.Utf8,
    "affected_entity_ids": pl.List(pl.Utf8),
}

CUSTOMER_DISPUTE_SCHEMA: dict[str, Any] = {
    "event_id": pl.Utf8,
    "event_type": pl.Utf8,
    "event_version": pl.Int64,
    "fraud_case_id": pl.Utf8,
    "fraud_alert_id": pl.Utf8,
    "fraud_record_id": pl.Utf8,
    "underlying_event_id": pl.Utf8,
    "payment_id": pl.Utf8,
    "customer_id": pl.Utf8,
    "account_id": pl.Utf8,
    "card_id": pl.Utf8,
    "device_id": pl.Utf8,
    "merchant_id": pl.Utf8,
    "event_time": _UTC_TIMESTAMP,
    "source_created_at": _UTC_TIMESTAMP,
    "source_available_at": _UTC_TIMESTAMP,
    "ingested_at": _UTC_TIMESTAMP,
    "processed_at": _UTC_TIMESTAMP,
    "producer": pl.Utf8,
    "source_system": pl.Utf8,
    "schema_version": pl.Utf8,
    "correlation_id": pl.Utf8,
    "causation_id": pl.Utf8,
    "simulation_run_id": pl.Utf8,
    "scenario_id": pl.Utf8,
    "scenario_type": pl.Utf8,
    "payment_rail": pl.Utf8,
    "payment_type": pl.Utf8,
    "amount": pl.Float64,
    "currency": pl.Utf8,
    "affected_entity_ids": pl.List(pl.Utf8),
}

FRAUD_LABEL_SCHEMA: dict[str, Any] = {
    "label_id": pl.Utf8,
    "fraud_case_id": pl.Utf8,
    "fraud_alert_id": pl.Utf8,
    "fraud_record_id": pl.Utf8,
    "customer_id": pl.Utf8,
    "payment_id": pl.Utf8,
    "event_id": pl.Utf8,
    "scenario_id": pl.Utf8,
    "scenario_type": pl.Utf8,
    "label": pl.Utf8,
    "fraud_truth": pl.Boolean,
    "fraud_occurred_at": _UTC_TIMESTAMP,
    "fraud_confirmed_at": _UTC_TIMESTAMP,
    "dispute_event_at": _UTC_TIMESTAMP,
    "label_available_at": _UTC_TIMESTAMP,
    "investigation_outcome": pl.Utf8,
    "amount": pl.Float64,
    "currency": pl.Utf8,
    "correlation_id": pl.Utf8,
    "causation_id": pl.Utf8,
    "simulation_run_id": pl.Utf8,
    "affected_entity_ids": pl.List(pl.Utf8),
}

LABEL_VERSION_SCHEMA: dict[str, Any] = {
    "label_version_id": pl.Utf8,
    "fraud_record_id": pl.Utf8,
    "payment_id": pl.Utf8,
    "case_id": pl.Utf8,
    "truth_label": pl.Boolean,
    "observed_label": pl.Utf8,
    "label_state": pl.Utf8,
    "investigation_selected": pl.Boolean,
    "label_version": pl.Int64,
    "label_available_at": _UTC_TIMESTAMP,
    "label_corrected_at": _UTC_TIMESTAMP,
    "case_reopened_at": _UTC_TIMESTAMP,
    "reason": pl.Utf8,
    "causation_id": pl.Utf8,
    "simulation_run_id": pl.Utf8,
}

FINAL_OBSERVED_LABEL_SCHEMA: dict[str, Any] = {
    "observation_id": pl.Utf8,
    "fraud_record_id": pl.Utf8,
    "payment_id": pl.Utf8,
    "observed_label": pl.Utf8,
    "label_state": pl.Utf8,
    "label_version": pl.Int64,
    "label_available_at": _UTC_TIMESTAMP,
    "label_corrected_at": _UTC_TIMESTAMP,
    "case_reopened_at": _UTC_TIMESTAMP,
    "investigation_selected": pl.Boolean,
    "simulation_run_id": pl.Utf8,
}

LABEL_CORRECTION_SCHEMA: dict[str, Any] = {
    "correction_id": pl.Utf8,
    "observation_id": pl.Utf8,
    "from_version": pl.Int64,
    "to_version": pl.Int64,
    "corrected_at": _UTC_TIMESTAMP,
    "observed_label": pl.Utf8,
    "truth_label": pl.Boolean,
    "causation_id": pl.Utf8,
}

CASE_REOPENING_SCHEMA: dict[str, Any] = {
    "reopening_id": pl.Utf8,
    "observation_id": pl.Utf8,
    "label_version": pl.Int64,
    "reopened_at": _UTC_TIMESTAMP,
    "reason": pl.Utf8,
    "causation_id": pl.Utf8,
}

OBSERVATION_PROVENANCE_SCHEMA: dict[str, Any] = {
    "observation_id": pl.Utf8,
    "policy_hash": pl.Utf8,
    "stream_ids": pl.List(pl.Utf8),
    "source_run_id": pl.Utf8,
}

BEHAVIOR_SCHEMAS: dict[str, dict[str, Any]] = {
    "behavior_profiles": BEHAVIOR_PROFILE_SCHEMA,
    "payments": PAYMENT_SCHEMA,
    "payment_events": PAYMENT_EVENT_SCHEMA,
    "ledger_entries": LEDGER_ENTRY_SCHEMA,
    "fraud_records": FRAUD_RECORD_SCHEMA,
    "fraud_alerts": FRAUD_ALERT_SCHEMA,
    "fraud_cases": FRAUD_CASE_SCHEMA,
    "case_confirmations": CASE_CONFIRMATION_SCHEMA,
    "customer_disputes": CUSTOMER_DISPUTE_SCHEMA,
    "fraud_labels": FRAUD_LABEL_SCHEMA,
}

COUNTERFACTUAL_CHANGE_SCHEMA: dict[str, Any] = {
    "change_set_id": pl.Utf8,
    "request_index": pl.Int64,
    "objective": pl.Utf8,
    "status": pl.Utf8,
    "source_payment_id": pl.Utf8,
    "derived_payment_id": pl.Utf8,
    "requested_budget": pl.Float64,
    "resolved_budget": pl.Float64,
    "effective_distance": pl.Float64,
    "per_dimension_costs": pl.Utf8,
    "changed_fields": pl.Utf8,
    "inapplicable_dimensions": pl.List(pl.Utf8),
    "feasibility_constraints": pl.List(pl.Utf8),
    "objective_satisfaction": pl.Utf8,
    "rejection_reason": pl.Utf8,
    "source_to_counterfactual": pl.Utf8,
}

COUNTERFACTUAL_WORKFLOW_SCHEMAS: dict[str, dict[str, Any]] = {
    "fraud_alerts": FRAUD_ALERT_SCHEMA,
    "fraud_cases": FRAUD_CASE_SCHEMA,
    "case_confirmations": CASE_CONFIRMATION_SCHEMA,
    "customer_disputes": CUSTOMER_DISPUTE_SCHEMA,
    "fraud_labels": FRAUD_LABEL_SCHEMA,
}
COUNTERFACTUAL_MASKED_WORKFLOW_FIELDS = {"fraud_cases", "case_confirmations", "fraud_labels"}

GRAPH_TRUTH_SCHEMAS: dict[str, dict[str, Any]] = {
    "campaigns": {
        "campaign_id": pl.Utf8,
        "scenario_type": pl.Utf8,
        "scenario_code": pl.Utf8,
        "truth_label": pl.Utf8,
        "valid_from": _UTC_TIMESTAMP,
        "valid_to": _UTC_TIMESTAMP,
        "participant_ids": pl.List(pl.Utf8),
        "modifiers": pl.List(pl.Utf8),
    },
    "campaign_memberships": GRAPH_MEMBERSHIP_SCHEMA,
    "patterns": GRAPH_PATTERN_SCHEMA,
    "graph_evidence": {
        "evidence_id": pl.Utf8,
        "edge_id": pl.Utf8,
        "evidence_type": pl.Utf8,
        "resource_id": pl.Utf8,
        "source_event_id": pl.Utf8,
        "payment_id": pl.Utf8,
        "observed_at": _UTC_TIMESTAMP,
        "available_at": _UTC_TIMESTAMP,
    },
    "hyperedges": {
        "hyperedge_id": pl.Utf8,
        "hyperedge_type": pl.Utf8,
        "campaign_id": pl.Utf8,
        "pattern_id": pl.Utf8,
        "valid_from": _UTC_TIMESTAMP,
        "valid_to": _UTC_TIMESTAMP,
        "source_event_ids": pl.List(pl.Utf8),
        "payment_ids": pl.List(pl.Utf8),
    },
    "hyperedge_memberships": {
        "hyperedge_id": pl.Utf8,
        "member_id": pl.Utf8,
        "member_type": pl.Utf8,
        "role": pl.Utf8,
    },
}

CAMPAIGN_DYNAMIC_SCHEMAS: dict[str, dict[str, Any]] = {
    "snapshots": {
        "snapshot_id": pl.Utf8,
        "campaign_id": pl.Utf8,
        "phase": pl.Utf8,
        "intensity": pl.Float64,
        "active_actor_ids": pl.List(pl.Utf8),
        "active_device_ids": pl.List(pl.Utf8),
        "valid_from": _UTC_TIMESTAMP,
        "valid_to": _UTC_TIMESTAMP,
        "transition_id": pl.Utf8,
    },
    "transitions": {
        "transition_id": pl.Utf8,
        "campaign_id": pl.Utf8,
        "from_phase": pl.Utf8,
        "to_phase": pl.Utf8,
        "occurred_at": _UTC_TIMESTAMP,
        "reason": pl.Utf8,
        "model_name": pl.Utf8,
        "source_snapshot_id": pl.Utf8,
        "stream_id": pl.Utf8,
    },
    "phase_changes": {
        "phase_change_id": pl.Utf8,
        "campaign_id": pl.Utf8,
        "transition_id": pl.Utf8,
        "phase": pl.Utf8,
        "valid_from": _UTC_TIMESTAMP,
        "valid_to": _UTC_TIMESTAMP,
    },
    "membership_changes": {
        "membership_change_id": pl.Utf8,
        "campaign_id": pl.Utf8,
        "actor_id": pl.Utf8,
        "actor_type": pl.Utf8,
        "role": pl.Utf8,
        "action": pl.Utf8,
        "occurred_at": _UTC_TIMESTAMP,
        "valid_from": _UTC_TIMESTAMP,
        "valid_to": _UTC_TIMESTAMP,
        "source_entity_id": pl.Utf8,
    },
    "intensity_decisions": {
        "intensity_decision_id": pl.Utf8,
        "campaign_id": pl.Utf8,
        "phase": pl.Utf8,
        "decision_at": _UTC_TIMESTAMP,
        "event_rate": pl.Float64,
        "mark": pl.Float64,
        "model_name": pl.Utf8,
        "stream_id": pl.Utf8,
    },
    "topology_mutations": {
        "topology_mutation_id": pl.Utf8,
        "campaign_id": pl.Utf8,
        "mutation_type": pl.Utf8,
        "occurred_at": _UTC_TIMESTAMP,
        "source_member_ids": pl.List(pl.Utf8),
        "derived_member_ids": pl.List(pl.Utf8),
        "source_payment_ids": pl.List(pl.Utf8),
        "derived_payment_ids": pl.List(pl.Utf8),
        "reason": pl.Utf8,
    },
    "lineage": {
        "lineage_id": pl.Utf8,
        "campaign_id": pl.Utf8,
        "parent_campaign_ids": pl.List(pl.Utf8),
        "source_entity_ids": pl.List(pl.Utf8),
        "source_event_ids": pl.List(pl.Utf8),
        "source_payment_ids": pl.List(pl.Utf8),
        "derived_entity_ids": pl.List(pl.Utf8),
        "derived_event_ids": pl.List(pl.Utf8),
        "derived_payment_ids": pl.List(pl.Utf8),
        "derived_at": _UTC_TIMESTAMP,
        "reason": pl.Utf8,
    },
    "source_snapshots": {
        "source_snapshot_id": pl.Utf8,
        "campaign_id": pl.Utf8,
        "source_run_id": pl.Utf8,
        "captured_at": _UTC_TIMESTAMP,
        "source_campaign_ids": pl.List(pl.Utf8),
        "source_entity_ids": pl.List(pl.Utf8),
        "source_event_ids": pl.List(pl.Utf8),
        "source_payment_ids": pl.List(pl.Utf8),
        "configuration_hash": pl.Utf8,
        "schema_fingerprint": pl.Utf8,
    },
}

CALIBRATION_METRIC_SCHEMA: dict[str, Any] = {
    "name": pl.Utf8,
    "version": pl.Utf8,
    "status": pl.Utf8,
    "score": pl.Float64,
    "weight": pl.Float64,
    "reference_summary_fingerprint": pl.Utf8,
    "generated_summary_fingerprint": pl.Utf8,
    "details": pl.Utf8,
}
