"""Optional Prometheus metrics for short-lived FraudTwin CLI jobs.

Metrics are deliberately kept outside generated manifests and configuration
hashes.  The CLI starts an isolated registry only when explicitly requested,
publishes run-level values, and holds the endpoint briefly so a local
Prometheus instance can scrape the completed batch job.
"""

import time
from collections.abc import Mapping
from typing import Any

from fraudtwin.manifest import RunManifest

_INVALID_FAULTS = frozenset(
    {
        "negative_amount",
        "invalid_enum",
        "invalid_reference",
        "corrupted_timestamp",
        "timezone_error",
        "schema_mismatch",
        "extreme_value",
        "encoding_error",
    }
)


class ObservabilityDependencyError(RuntimeError):
    """Raised when metrics are requested without the optional dependency."""


class MetricsSession:
    """Expose the stable M27 metric surface for one CLI invocation."""

    def __init__(self, host: str, port: int, hold_seconds: float = 15.0) -> None:
        if not host:
            raise ValueError("metrics host must not be empty")
        if port < 1 or port > 65_535:
            raise ValueError("metrics port must be between 1 and 65535")
        if hold_seconds < 0:
            raise ValueError("metrics hold seconds must be non-negative")
        self.host = host
        self.port = port
        self.hold_seconds = hold_seconds
        self._server: Any | None = None
        self._thread: Any | None = None
        self.registry: Any | None = None
        self._run_id = "unknown"
        self._events: Any = None
        self._events_per_second: Any = None
        self._fraud_events: Any = None
        self._errors: Any = None
        self._duplicate_rate: Any = None
        self._late_events: Any = None
        self._invalid_rate: Any = None
        self._ledger_failures: Any = None

    def start(self) -> None:
        """Start the local exposition endpoint."""

        try:
            from prometheus_client import CollectorRegistry, Counter, Gauge, start_http_server
        except ImportError as exc:  # pragma: no cover - depends on optional extra
            raise ObservabilityDependencyError(
                "metrics output requires the optional 'observability' dependency"
            ) from exc

        registry = CollectorRegistry()
        self.registry = registry
        self._events = Counter(
            "events_generated_total",
            "Observable payment events generated by FraudTwin.",
            ("run_id",),
            registry=registry,
        )
        self._events_per_second = Gauge(
            "events_generated_per_second",
            "Average observable payment-event generation rate.",
            ("run_id",),
            registry=registry,
        )
        self._fraud_events = Counter(
            "fraud_events_total",
            "True scenario-linked fraud events generated by FraudTwin.",
            ("run_id",),
            registry=registry,
        )
        self._errors = Counter(
            "generator_errors_total",
            "Failed FraudTwin generation invocations.",
            ("run_id",),
            registry=registry,
        )
        self._duplicate_rate = Gauge(
            "duplicate_rate",
            "Duplicate output-row rate across observable generated tables.",
            ("run_id",),
            registry=registry,
        )
        self._late_events = Gauge(
            "late_event_count",
            "Late events injected into the generated payment-event stream.",
            ("run_id",),
            registry=registry,
        )
        self._invalid_rate = Gauge(
            "invalid_record_rate",
            "Rate of observable rows targeted by invalidating quality faults.",
            ("run_id",),
            registry=registry,
        )
        self._ledger_failures = Gauge(
            "ledger_reconciliation_failures",
            "Whether ledger validation failed for the selected run.",
            ("run_id",),
            registry=registry,
        )
        self._server, self._thread = start_http_server(self.port, addr=self.host, registry=registry)

    def _labels(self, run_id: str) -> tuple[Any, ...]:
        if self._events is None:
            raise RuntimeError("metrics session has not started")
        self._run_id = run_id
        labels = (run_id,)
        # Initialize every series so a clean run still exposes zero-valued DQ
        # and failure metrics.
        for metric in (
            self._events,
            self._events_per_second,
            self._fraud_events,
            self._errors,
            self._duplicate_rate,
            self._late_events,
            self._invalid_rate,
            self._ledger_failures,
        ):
            metric.labels(*labels)
        return labels

    @staticmethod
    def _mapping(value: object) -> Mapping[str, Any]:
        return value if isinstance(value, Mapping) else {}

    @classmethod
    def _calculate_duplicate_rate(cls, diagnostics: object) -> float:
        uniqueness = cls._mapping(cls._mapping(diagnostics).get("key_uniqueness"))
        rows = 0
        duplicates = 0
        for table in ("payments", "payment_events", "fraud_records"):
            summary = cls._mapping(uniqueness.get(table))
            rows += int(summary.get("rows", 0) or 0)
            duplicates += int(summary.get("duplicate_rows", 0) or 0)
        return duplicates / rows if rows else 0.0

    @classmethod
    def _calculate_invalid_record_rate(cls, diagnostics: object, fallback_rows: int) -> float:
        payload = cls._mapping(diagnostics)
        uniqueness = cls._mapping(payload.get("key_uniqueness"))
        denominator = sum(
            int(cls._mapping(uniqueness.get(table)).get("rows", 0) or 0)
            for table in ("payments", "payment_events")
        )
        if not denominator:
            denominator = fallback_rows
        targets = {
            str(entry.get("target"))
            for entry in payload.get("fault_audit", [])
            if isinstance(entry, Mapping)
            and entry.get("fault") in _INVALID_FAULTS
            and entry.get("target") is not None
        }
        return len(targets) / denominator if denominator else 0.0

    def observe_manifest(self, manifest: RunManifest, elapsed_seconds: float) -> None:
        """Publish final generation metrics from the immutable run manifest."""

        labels = self._labels(manifest.run_id)
        event_count = int(manifest.event_counts.get("payment_events", 0))
        fraud_count = int(manifest.fraud_counts.get("fraud_events", 0))
        rows = event_count + int(manifest.event_counts.get("payments", 0))
        self._events.labels(*labels).inc(event_count)
        self._events_per_second.labels(*labels).set(event_count / max(float(elapsed_seconds), 1e-9))
        self._fraud_events.labels(*labels).inc(fraud_count)
        self._duplicate_rate.labels(*labels).set(
            self._calculate_duplicate_rate(manifest.quality_diagnostics)
        )
        self._late_events.labels(*labels).set(
            int(manifest.quality_fault_counts.get("late_events", 0))
        )
        self._invalid_rate.labels(*labels).set(
            self._calculate_invalid_record_rate(manifest.quality_diagnostics, rows)
        )
        self._ledger_failures.labels(*labels).set(0)

    def record_generator_error(self) -> None:
        """Count a failed generation invocation without hiding its exception."""

        if self._errors is None:
            raise RuntimeError("metrics session has not started")
        self._errors.labels(self._run_id).inc()

    def record_ledger_validation(self, run_id: str, failed: bool) -> None:
        """Record the result of the existing ledger validator."""

        labels = self._labels(run_id)
        self._ledger_failures.labels(*labels).set(1 if failed else 0)

    def finish(self) -> None:
        """Hold the endpoint for scraping, then stop its serving thread."""

        if self._server is None:
            return
        if self.hold_seconds:
            time.sleep(self.hold_seconds)
        self._server.shutdown()
        self._server.server_close()
        if self._thread is not None:
            self._thread.join(timeout=2)
        self._server = None
        self._thread = None
        self.registry = None


__all__ = ["MetricsSession", "ObservabilityDependencyError"]
