"""Prepare a sphinx-multiversion output tree for GitHub Pages."""

import json
import shutil
import sys
from pathlib import Path

TUTORIAL_ALIASES = {
    "tutorials/28-calibration-reference-data.html": (
        "tutorials/calibration-and-counterfactuals.html"
    ),
    "tutorials/29-counterfactual-fraud-experiments.html": (
        "tutorials/calibration-and-counterfactuals.html"
    ),
    "tutorials/30-campaign-dynamics-fraud-rings.html": (
        "tutorials/campaign-graph-investigation.html"
    ),
    "tutorials/31-external-predictions-backtesting.html": (
        "tutorials/ml-shift-and-backtesting.html"
    ),
    "tutorials/32-observable-oracle-investigation.html": (
        "tutorials/campaign-graph-investigation.html"
    ),
    "tutorials/33-scale-resource-benchmarking.html": (
        "tutorials/scale-reconciliation-and-reproducibility.html"
    ),
    "tutorials/34-multi-rail-payment-reconciliation.html": (
        "tutorials/scale-reconciliation-and-reproducibility.html"
    ),
    "tutorials/35-reproducible-experiment-packaging.html": (
        "tutorials/scale-reconciliation-and-reproducibility.html"
    ),
}


def _write_redirect(path: Path, target: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    relative_target = target.removeprefix("tutorials/")
    path.write_text(
        f'<!doctype html><meta http-equiv="refresh" content="0; url=../{relative_target}">'
        f'<link rel="canonical" href="../{relative_target}">\n',
        encoding="utf-8",
    )


def _write_tutorial_aliases(output: Path) -> None:
    for alias, target in TUTORIAL_ALIASES.items():
        _write_redirect(output / alias, target)


def prepare_site(root: Path) -> None:
    root = root.resolve()
    candidates = sorted(
        path
        for path in root.iterdir()
        if path.is_dir() and (path.name in {"main", "dev"} or path.name.startswith("v"))
    )
    if not candidates:
        raise SystemExit(f"no sphinx-multiversion outputs found in {root}")
    main_output = next((path for path in candidates if path.name in {"main", "dev"}), candidates[0])
    latest = root / "latest"
    if latest.exists():
        shutil.rmtree(latest)
    shutil.copytree(main_output, latest)
    _write_tutorial_aliases(latest)
    versions = [
        {
            "name": "latest",
            "version": "latest",
            "url": "https://emedinac.github.io/fraudtwin/latest/",
        }
    ]
    for path in candidates:
        if path.name in {"main", "dev"}:
            continue
        _write_tutorial_aliases(path)
        versions.append(
            {
                "name": path.name,
                "version": path.name,
                "url": f"https://emedinac.github.io/fraudtwin/{path.name}/",
            }
        )
    (root / "version-switcher.json").write_text(
        json.dumps(versions, indent=2) + "\n", encoding="utf-8"
    )
    (root / "index.html").write_text(
        '<!doctype html><meta http-equiv="refresh" content="0; url=latest/">'
        '<link rel="canonical" href="latest/">\n',
        encoding="utf-8",
    )
    # Preserve the pre-versioning API URL used by README files, bookmarks, and
    # external references.  The API page itself remains generated by Sphinx at
    # ``latest/api.html`` (and under each release directory).
    (root / "api.html").write_text(
        '<!doctype html><meta http-equiv="refresh" content="0; url=latest/api.html">'
        '<link rel="canonical" href="latest/api.html">\n',
        encoding="utf-8",
    )


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: prepare_site.py BUILD_DIRECTORY")
    prepare_site(Path(sys.argv[1]))


if __name__ == "__main__":
    main()
